import { test,expect } from '@playwright/test';
test('create, execute, inspect, schedule, and restrict a real workflow',async ({page,request}) => {
  test.setTimeout(120000);
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Your work. On autopilot.'})).toBeVisible();
  await expect(page.getByText('Local runtime connected',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
  const name = `Fixture ${Date.now()}`;
  await page.getByRole('button',{name:'Create workflow',exact:true}).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Workflow name').fill(name);
  await dialog.getByLabel('Approved website origins').fill('http://127.0.0.1:3100');
  await dialog.getByLabel('Page URL').fill('http://127.0.0.1:3100/fixture.html');
  await dialog.getByRole('button',{name:'Add step',exact:true}).click();
  await dialog.getByLabel('Element selector').fill('h1');
  await dialog.getByRole('button',{name:'Save workflow'}).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button',{name:`Run ${name}`,exact:true}).click();
  await expect(page.getByRole('dialog').getByText('All steps completed.')).toBeVisible({timeout:45000});
  await expect(page.getByRole('dialog').getByText('Automation verified',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('navigation').getByRole('button',{name:'Schedules',exact:true}).click();
  await page.getByRole('button',{name:'Create schedule',exact:true}).first().click();
  await page.getByLabel('Schedule name').fill(`Schedule ${name}`);
  await page.getByLabel('Workflow',{exact:false}).selectOption({label:`${name} · revision 1`});
  await page.getByLabel('Cron expression').fill('* * * * *');
  await page.getByRole('button',{name:'Save schedule'}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect.poll(async () => {
    const state = await (await request.get('/api/workspace',{headers:{'x-barmeto-client':'workspace'}})).json();
    return state.runs.some(r => r.name === name && r.source !== 'manual' && r.status === 'succeeded');
  },{timeout:75000,intervals:[1000,2000]}).toBe(true);
  await page.getByRole('navigation').getByRole('button',{name:'Task rules'}).click();
  await page.getByRole('button',{name:'Add rule',exact:true}).click();
  await page.getByLabel('Rule name').fill(`Blocked ${name}`);
  await page.getByLabel('Hostname').fill('127.0.0.1');
  await page.getByRole('button',{name:'Save rule'}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  const state = await (await request.get('/api/workspace',{headers:{'x-barmeto-client':'workspace'}})).json();
  const wf = state.workflows.find(w => w.name === name);
  const blocked = await request.post('/api/workspace',{headers:{'x-barmeto-client':'workspace'},data:{type:'run',id:wf.id}});
  expect(blocked.status()).toBe(400);
  expect((await blocked.json()).error).toContain('Blocked by rule');
  for(const rule of state.rules) await request.post('/api/workspace',{headers:{'x-barmeto-client':'workspace'},data:{type:'delete-rule',id:rule.id}});
});
test('local API rejects cross-origin callers and page fits a narrow viewport',async ({page,request}) => {
  expect((await request.get('/api/workspace')).status()).toBe(403);
  expect((await request.post('/api/workspace',{headers:{'x-barmeto-client':'workspace',origin:'https://untrusted.example'},data:{type:'settings',headless:false}})).status()).toBe(403);
  await page.setViewportSize({width:390,height:844});
  await page.goto('/');
  const overflow = await page.evaluate(() => ({ width:document.documentElement.scrollWidth, viewport:window.innerWidth, elements:[...document.querySelectorAll('body *')].filter(el => el.getBoundingClientRect().right > window.innerWidth + 1).map(el => ({ tag:el.tagName,class:el.className,width:el.getBoundingClientRect().width })).slice(0,15) }));
  expect(overflow.width,JSON.stringify(overflow)).toBeLessThanOrEqual(overflow.viewport);
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.getByRole('navigation').getByRole('button',{name:'Workflows'}).click();
  await expect(page.getByRole('heading',{name:'Build once. Run whenever.'})).toBeVisible();
  await page.screenshot({path:'test-results/workflows-mobile.png',fullPage:true});
});
