'use client';
import { useEffect,useState } from 'react';
import { createClient } from '@supabase/supabase-js';
export default function Admin() {
  const [client,setClient] = useState(null),[session,setSession] = useState(null),[email,setEmail] = useState(''),[otp,setOtp] = useState(''),[sent,setSent] = useState(false),[factor,setFactor] = useState(null),[code,setCode] = useState(''),[data,setData] = useState(null),[page,setPage] = useState('Applications'),[message,setMessage] = useState(''),[busy,setBusy] = useState(false),[form,setForm] = useState({});
  useEffect(() => { const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY; if(!url || !key) return; const c=createClient(url,key,{auth:{persistSession:false}}); setClient(c); const {data}=c.auth.onAuthStateChange((_e,s) => setSession(s)); return () => data.subscription.unsubscribe(); },[]);
  async function operation(fn) { setBusy(true); setMessage(''); try { await fn(); } catch(e) { setMessage(e.message); } finally {setBusy(false);} }
  async function manage(action,value) {
    const {data:auth} = await client.auth.getSession();
    const response = await fetch('/api/manage',{method:action?'POST':'GET',headers:{Authorization:`Bearer ${auth.session?.access_token}`,'Content-Type':'application/json'},...(action?{body:JSON.stringify({action,value})}:{})});
    const result=await response.json(); if(!response.ok) throw Error(result.error); if(!action) setData(result); return result;
  }
  async function prepareMfa() {
    const {data:level,error}=await client.auth.mfa.getAuthenticatorAssuranceLevel(); if(error) throw error;
    if(level.currentLevel==='aal2') {await manage();return;}
    const factors=await client.auth.mfa.listFactors(); if(factors.error) throw factors.error;
    if(factors.data.totp.length) setFactor({id:factors.data.totp[0].id});
    else {const enrollment=await client.auth.mfa.enroll({factorType:'totp',friendlyName:`Barmeto ${Date.now()}`});if(enrollment.error) throw enrollment.error;setFactor(enrollment.data);}
  }
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  return <div className="admin-shell"><aside><a className="logo" href="/">barmeto<span>.</span><small>MASTER ADMIN</small></a><p className="nav-label">CONTROL CENTER</p>{['Applications','Versions','Task rules','Email & OTP','Audit log'].map(name=><button className={page===name?'active':''} key={name} onClick={()=>{setPage(name);setForm({});}}>{name}</button>)}<div className="aside-note">Hosted administration<br/>Protected by Supabase Auth + MFA</div></aside><main><header><div><small>ADMINISTRATION / {page.toUpperCase()}</small><h1>{page}</h1><p>Manage your platform with clear permissions and a record of every change.</p></div>{session&&<button onClick={()=>operation(async()=>{await client.auth.signOut();setData(null);setFactor(null);setSent(false);})}>Sign out</button>}</header>{message&&<div className="notice" role="status">{message}</div>}
    {!client ? <section><h2>Connect your admin deployment</h2><p>Add the Supabase URL and publishable key to <code>admin/.env.local</code>, apply the migrations, and bootstrap your administrator. No service-role key is needed in this interface.</p></section> : !data ? <section className="auth"><h2>{!session?'Sign in to administration':factor?'Verify your authenticator':'Verify administrator access'}</h2>{!session?<form onSubmit={e=>{e.preventDefault();operation(async()=>{const r=sent?await client.auth.verifyOtp({email,token:otp,type:'email'}):await client.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(r.error)throw r.error;setSent(true);setMessage(sent?'Signed in. Continue with your authenticator.':'If this account is eligible, a sign-in email has been requested.');});}}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={sent}/></label>{sent&&<label>Email code<input required autoComplete="one-time-code" value={otp} onChange={e=>setOtp(e.target.value)}/></label>}<button className="primary" disabled={busy}>{sent?'Verify email code':'Send sign-in code'}</button></form>:factor?<form onSubmit={e=>{e.preventDefault();operation(async()=>{const r=await client.auth.mfa.challengeAndVerify({factorId:factor.id,code});if(r.error)throw r.error;await manage();setFactor(null);});}}>{factor.totp&&<><p>Scan this code with your authenticator. Keep its secret private.</p><img className="qr" alt="Authenticator enrollment QR code" src={factor.totp.qr_code}/><details><summary>Manual setup secret</summary><code>{factor.totp.secret}</code></details></>}<label>Authenticator code<input required autoComplete="one-time-code" inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)}/></label><button className="primary" disabled={busy}>Verify and open</button></form>:<><p>An active master-admin role and a verified authenticator are required. Email sign-in alone does not grant access.</p><button className="primary" disabled={busy} onClick={()=>operation(prepareMfa)}>Continue securely</button></>}</section>:<>
    <div className="summary"><section><small>Registered applications</small><strong>{data.applications.length}</strong></section><section><small>Live applications</small><strong>{data.applications.filter(a=>a.status==='live').length}</strong></section><section><small>Release records</small><strong>{data.releases.length}</strong></section></div>
    {page==='Applications'&&<><section><h2>Register application</h2><form className="inline-form" onSubmit={e=>{e.preventDefault();operation(async()=>{await manage('create-application',{name:form.name,slug:form.slug,description:form.description||''});setForm({});await manage();});}}><label>Name<input required minLength={2} value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Immutable slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug||''} onChange={e=>set('slug',e.target.value)}/></label><button className="primary" disabled={busy}>Register</button></form></section><section><h2>Application availability</h2><p>Live means available to authorized members. Offline devices cannot receive immediate revocation.</p>{data.applications.map(a=><div className="row" key={a.id}><div><strong>{a.name}</strong><small>{a.slug}</small></div><select aria-label={`${a.name} status`} value={a.status} disabled={busy} onChange={e=>{const status=e.target.value;if(window.confirm(`Set ${a.name} to ${status}?`))operation(async()=>{await manage('application-status',{id:a.id,status});await manage();});}}>{['draft','live','paused','retired'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section></>}
    {page==='Versions'&&<><section><h2>Reserve a release draft</h2><p>Version reservation is transactional. Installer build, signing, and verified publication are still required before a draft becomes downloadable.</p><form onSubmit={e=>{e.preventDefault();operation(async()=>{await manage('draft-release',{applicationId:form.app,changeType:form.bump||'patch',notes:form.notes});setForm({});await manage();});}}><div className="inline-form"><label>Application<select required value={form.app||''} onChange={e=>set('app',e.target.value)}><option value="">Choose application</option>{data.applications.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Change type<select value={form.bump||'patch'} onChange={e=>set('bump',e.target.value)}><option value="patch">Patch — fixes</option><option value="minor">Minor — new features</option><option value="major">Major — breaking changes</option></select></label></div><label>Release notes<textarea required minLength={5} value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></label><button className="primary" disabled={busy}>Reserve version</button></form></section><section>{data.releases.map(r=><div className="row" key={r.id}><div><strong>{data.applications.find(a=>a.id===r.application_id)?.name} · v{r.version}</strong><small>{r.notes}</small></div><span className="badge">{r.status}</span></div>)}</section></>}
    {page==='Task rules'&&<><section><h2>Add a platform rule</h2><p>These cloud records are stored centrally. Device policy synchronization is not enabled in the first desktop build.</p><form onSubmit={e=>{e.preventDefault();operation(async()=>{await manage('save-rule',{name:form.name,type:form.type||'block-domain',value:form.value||''});setForm({});await manage();});}}><div className="inline-form"><label>Name<input required value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Type<select value={form.type||'block-domain'} onChange={e=>set('type',e.target.value)}><option value="block-domain">Block domain</option><option value="max-steps">Maximum steps</option><option value="disable-schedules">Block schedules</option></select></label><label>Value<input value={form.value||''} onChange={e=>set('value',e.target.value)}/></label><button className="primary" disabled={busy}>Add rule</button></div></form></section><section>{data.rules.filter(r=>!r.archived).map(r=><div className="row" key={r.id}><div><strong>{r.name}</strong><small>{r.definition.type} · {r.definition.value}</small></div><button disabled={busy} onClick={()=>{if(window.confirm(`Archive ${r.name}?`))operation(async()=>{await manage('archive-rule',{id:r.id});await manage();});}}>Archive rule</button></div>)}</section></>}
    {page==='Email & OTP'&&<section><h2>Authentication delivery setup</h2><p>Configure a verified SMTP sender and an email-code template in Supabase Auth. This panel never exposes user codes or SMTP secrets.</p><ol><li>Verify your sending domain with your provider.</li><li>Configure custom SMTP in Supabase Auth.</li><li>Use the token variable in the email template for OTP sign-in.</li><li>Configure rate limits and test delivery to an approved address.</li></ol><p>Transactional notification queues, provider delivery webhooks, and editable email templates are not connected yet. No delivery status is fabricated.</p></section>}
    {page==='Audit log'&&<section><h2>Recent administrative changes</h2>{data.audit.map(a=><div className="row" key={a.id}><div><strong>{a.action}</strong><small>{a.target_id}</small></div><small>{new Date(a.occurred_at).toLocaleString()}</small></div>)}</section>}
    <button disabled={busy} onClick={()=>operation(()=>manage())}>Refresh data</button></>}
    <footer>Changes are checked by the server and Supabase policies. This panel is separate from the desktop installer.</footer></main></div>;
}
